services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  db:
    image: postgres:16.1
    container_name: shareit
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dbuser
      - POSTGRES_USER=12345
      - POSTGRES_DB=shareitdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  dbtest:
    image: postgres:16.1
    container_name: shareit-db-test
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=shareitdbtest